frontend:
  tag: staging-latest
  apiBaseUrl: http://ml-staging.cern.ch/challenges/api
  sso:
    clientId: challenges-staging
    enable: "false"

backend:
  tag: staging-latest
  debug: "True"
  databaseUrl: <path:kv/data/mlops/services/challenges/staging/db#connection_url#1>
  sso:
    audience: challenges-staging
  
  kubeflow:
    url: https://ml-staging.cern.ch
