frontend:
  tag: staging-latest
  apiBaseUrl: http://ml-staging.cern.ch/challenges/api
  sso:
    clientId: challenges-staging

backend:
  tag: staging-latest
  debug: "True"
  sso:
    audience: challenges-staging
  
  kubeflow:
    url: https://ml-staging.cern.ch
