{{- if .Values.istio.enableVirtualService}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: challenges-frontend-vs
spec:
  hosts:
  - challenges.ml.cern.ch
  http:
  - match:
    - uri:
        prefix: "/api"
    route:
    - destination:
        host: backend-svc.challenges.svc.cluster.local
        port: 80
  - route:
    - destination:
        host: frontend-svc.challenges.svc.cluster.local
        port: 80
{{- else }}
{{- end }}