{{- if .Values.istio.enableVirtualService}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: challenges-frontend-vs
spec:
  gateways:
    ## the istio gateway which is serving kubeflow
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    # Backend
    - match:
        - uri:
            prefix: /challenges/api
      rewrite:
        uri: /
      route:
        - destination:
            host: backend-svc.challenges.svc.cluster.local
            port: 80

    # UI
    - match:
        - uri:
            prefix: /challenges/ui
      rewrite:
        uri: /
      route:
        - destination:
            host: frontend-svc.challenges.svc.cluster.local
            port: 80
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: "challenges"
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods: ["GET", "POST", "DELETE", "PATCH", "PUT"]

{{- else }}
{{- end }}
